### ISSUE TITLE
Method  Kaui::KillbillHelper::get_bundle_by_key throws an exception for valid data

### ISSUE THREAD

**Issue by farialima** [killbill/killbill-admin-ui#26]
when using Kaui::KillbillHelper::get_bundle_by_key with an external key as 'key' parameter, the following exception will occur if the bundle has two or more subscriptions (one active, and some more cancelled).  We have this exception in a custom UI we have created, and I believe we use the API as expected.

The exception stack is:

```
 comparison of String with Time failed
'gems/kaui-0.6.6/app/helpers/kaui/killbill_helper.rb:171:in `get_active_bundle_or_latest_created
'gems/kaui-0.6.6/app/helpers/kaui/killbill_helper.rb:164:in `get_active_bundle_or_latest_created
'gems/kaui-0.6.6/app/helpers/kaui/killbill_helper.rb:163:in `get_active_bundle_or_latest_created
'gems/kaui-0.6.6/app/helpers/kaui/killbill_helper.rb:603:in `get_active_bundle_or_latest_created
'gems/kaui-0.6.6/app/helpers/kaui/killbill_helper.rb:150:in `get_bundle_by_key
'gems/kaui-0.6.6/app/helpers/kaui/killbill_helper.rb:603:in `get_bundle_by_key
```

the issue is at https://github.com/killbill/killbill-admin-ui/blob/v0.6.6/app/helpers/kaui/killbill_helper.rb#L171 - "s.cancelled_date" is a string (formatted YYYY-MM-DD e.g. "2013-05-19")

A possible fix would be to change that line 171 from:

```
            if s.cancelled_date.nil? || s.cancelled_date > Time.now
```

to

```
            if s.cancelled_date.nil? || s.cancelled_date > Time.now.strftime("%F")
```

although I'm not clear what would happen on the cancelation _day_ itself...

**Comment by pierre** [comment]
The code is now here: https://github.com/killbill/killbill-admin-ui/blob/master/app/models/kaui/bundle.rb#L42

**Comment by pierre** [comment]
To summarize the issue, the problem is: https://github.com/killbill/killbill-admin-ui/blob/7dc572a6a02e3b8f646c665dbf630b425b6c09d4/app/helpers/kaui/subscription_helper.rb#L103

* `cancelledDate` is already a `LocalDate` in the account time zone. No need to call `format_date`
* The comparison should use the `@clock` instead of `Time.now`
* The comparison should be done in the account time zone (i.e. convert the time from `clock` into a date object representing `today` in the account timezone)

As part of this, we should fix similar invocation of `Time.now` throughout the code (e.g. in app/models/kaui/bundle.rb as well).
