### ISSUE TITLE
Make the Kaui Sign In Page Error 500 more informative

### ISSUE THREAD

**Issue by KBbitsP** [killbill/killbill-admin-ui#330]
Description : In the cases when there is some issue with Kaui login and it encounters error 500, the browser just shows "We're sorry, but something went wrong."

Requirement : To make the error page to display more information about the actual error. 

![image](https://user-images.githubusercontent.com/75751774/208484805-96348f09-9fe3-47c0-99f4-9b83538a0066.png)

**Comment by tungleduyxyz** [comment]
Hi @pierre, 
I see this is our default 500 error page.
+ I can override this but do you have any specific requirements for this page or maybe a design template?
+ I think we should handle the exceptions when login, in case it's 5xx error, we should only display the error message like "Unable to login, please try again." instead of displaying an error page.

**Comment by pierre** [comment]
> I can override this but do you have any specific requirements for this page or maybe a design template?

Could you do something simple for now, e.g. just show a box with the raw error details (with stacktrace if available)
<img width="487" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/51940/81e0693d-764d-43a6-8ad1-3aa84cc68bbe">

> I think we should handle the exceptions when login, in case it's 5xx error, we should only display the error message like "Unable to login, please try again." instead of displaying an error page.

Yes, whenever it's possible and we understand the error, let's use flash messages and/or show something very helpful/user friendly.

**Comment by tungleduyxyz** [comment]
Hi @pierre I found that the environment in this ticket was Docker, and with docker we run the applications as production environment. That's why the app hides the raw error. 
Here are the configs of the production and development environment:
**Development**: https://github.com/killbill/killbill-admin-ui-standalone/blob/d563498ddc36b9841d32fc025b2c57a87705ffea/config/environments/development.rb#L18
**Production**: https://github.com/killbill/killbill-admin-ui-standalone/blob/d563498ddc36b9841d32fc025b2c57a87705ffea/config/environments/production.rb#L16C25-L16C25

The difference when the config is on/off:
<img width="1032" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/80109474/198e6ddd-9056-4b22-940b-7f7221dafc3f">
<img width="1032" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/80109474/097e5018-8985-4b26-ac2a-02858f2096e7">

**Comment by tungleduyxyz** [comment]
I suggest that we can use another environment variable like DOCKER_DEVELOPMENT_MODE=true.
And using this variable to set **config.consider_all_requests_local** true or false

**Comment by KBbitsP** [comment]
Hi @tungleduyxyz I believe I was using tomcat deployment for reproducing the error shown in the first comment.

**Comment by KBbitsP** [comment]
Test Results :

Wrong DB password : 


![image (9)](https://github.com/killbill/killbill-admin-ui/assets/75751774/b95ab23b-211e-4854-a7d7-b364feb69630)

Database down : 

![image (10)](https://github.com/killbill/killbill-admin-ui/assets/75751774/50fd3886-fcf2-4f4e-8851-3749ec265903)

Kill Bill server down : 

![image (11)](https://github.com/killbill/killbill-admin-ui/assets/75751774/5410c192-fd01-4858-beb4-3a5b00271b76)
