### ISSUE TITLE
Logging-in with a user with no configure tenants prompts for creating a tenant

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-admin-ui#68]
When using default `admin` user, all existing tenants will automatically be part of the selection list -- assuming at least one tenant exists because of this [code](https://github.com/killbill/killbill-admin-ui/blob/work-for-release-0.17.x/app/controllers/kaui/engine_controller.rb#L37).

However when logging-in with a user that has no configured tenant, the user gets redirected to [create a new tenant](https://github.com/killbill/killbill-admin-ui/blob/work-for-release-0.17.x/app/controllers/kaui/tenants_controller.rb#L21).

Interestingly, the screen only allows to create new tenant (and so if user just wants to use an existing tenant), no luck this will not work (tenant creation will fail).

**Comment by sbrossie** [comment]
This issue is interesting for the following reasons:
1. Should we support a mode where no tenant is selected for the user (this could be interesting for all cross tenant operations, including the ability to create tenants in the first place). By the way today we always force user to chose a tenant (which does not work in the bootstraping phase if no tenant exist at all)
2. If not, we should at least change that screen to do a soft tenant creation (where operation does not fail if tenant already exists)

**Comment by sbrossie** [comment]
Another option would be to have KAUI discover the tenants. I think we did not implement that because we need the `api_secret` for the tenant. Maybe KAUI could prompt for list of existing tenants, and the process of adding a new tenant for a specific user would require entering the `api_secret` (at least first time).

**Comment by sbrossie** [comment]
Code change above c93c4cc1 fixes the issue where user is prompted with a 'Add new tenant' screen and when he tries to add an existing tenant (in KAUI) things fail because of duplicate entry. That solves the initial problem and is probably good enough for now, but leaving issue open to (maybe one day) improve the flow and allow a mode where cross tenant screen don't require choosing a tenant.

**Comment by pierre** [comment]
> leaving issue open to (maybe one day) improve the flow and allow a mode where cross tenant screen don't require choosing a tenant.

The issue is still present, i.e. cross tenant screens still require the user to choose a tenant.

For example, if signed-out and one tries to go to http://127.0.0.1:3000/admin_tenants (cross tenant screen), the user will be prompted to sign-in (as expected), then choose a tenant (doesn't make sense for that screen) and is eventually redirected to http://127.0.0.1:3000/admin_tenants.

The work is to remove the need to select/create a tenant for cross-tenant screens, such as `/admin_allowed_users`, `/admin_tenants` and `/admin`. If the user tries to go to any other screen after this (e.g. home page or create account page), he should be prompted to select a tenant. If he chooses to go to a specific tenant page (e.g. `/admin_tenants/1`), the tenant should then be auto-selected (I believe it is already the case today, to be verified).

Some plugin screens may not require a tenant configured (e.g. `kpm` one) but I wouldn't bother for these, as we don't have a good contract for the UI plugins to tell us whether a tenant is required or not. I would just focus on finding the core screens that do not require a tenant to be configured (the three listed above might actually be the extended list).
